version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"
    target-branch: "main"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build:"
    target-branch: "main"
    groups:
      "net.kyori":
        patterns:
          - "net.kyori*"
