[versions]
# kotlin
kotlin = "2.0.21"
coroutines = "1.6.4"

license = "0.16.1"

# Core
annotations = "24.1.0"
guava = "33.2.0-jre"
logger = "2.0.13"
nova = "1.0.0-SNAPSHOT"

# Minecraft
adventure = "4.16.0"
paper = "1.21.1-R0.1-SNAPSHOT"

# Build
run-paper = "2.3.1"
resource-factory = "1.2.0"
shadow = "8.3.3"

[libraries]
# Core
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
logger = { module = "org.slf4j:slf4j-api", version.ref = "logger" }
nova = { module = "dev.triumphteam:nova", version.ref = "nova" }
nova-kotlin = { module = "dev.triumphteam:nova-kotlin", version.ref = "nova" }

# Minecraft
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# Kotlin
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# Build
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
build-license = { module = "gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin", version.ref = "license" }
build-run-paper = { module = "xyz.jpenilla:run-task", version.ref = "run-paper" }
build-resource-factory = { module = "xyz.jpenilla:resource-factory", version.ref = "resource-factory" }
build-shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

[bundles]
build = [
    "build-kotlin",
    "build-license",
]
paper-examples = [
    "build-run-paper",
    "build-resource-factory",
    "build-shadow",
]
